"""Integration tests for nested condition rules with the evaluator.

Tests that rules with nested conditions can be generated by the wizard
and correctly evaluated by the rule engine.
"""

import json
import pytest

from core.tools.rule_wizard_core import (
    RuleBuilder,
    GroupingSpec,
    ConditionGroup,
)
from core.rule_engine import _evaluate_condition_node


class TestNestedConditionsEvaluation:
    """Test evaluation of rules with nested conditions."""

    def test_evaluator_accepts_nested_any_all(self):
        """Test that evaluator handles nested any/all structures."""
        # Create a nested condition: all [ FROM, any [ SUBJECT patterns ] ]
        header = {"from": "steve.gibson@metoffice.gov.uk", "subject": "Accepted:"}

        condition = {
            "all": [
                {
                    "header": "from",
                    "contains": "steve.gibson@metoffice.gov.uk",
                },
                {
                    "any": [
                        {"header": "subject", "contains": "Accepted:"},
                        {"header": "subject", "contains": "Tentative:"},
                        {"header": "subject", "contains": "Declined:"},
                    ]
                },
            ]
        }

        # Should match - from matches AND (Accepted: matches in any group)
        result = _evaluate_condition_node(header, condition, {}, "")
        assert result is True

    def test_evaluator_rejects_when_from_no_match(self):
        """Test evaluation fails when required FROM condition doesn't match."""
        header = {
            "from": "wrong@example.com",
            "subject": "Accepted:",
        }

        condition = {
            "all": [
                {
                    "header": "from",
                    "contains": "steve.gibson@metoffice.gov.uk",
                },
                {
                    "any": [
                        {"header": "subject", "contains": "Accepted:"},
                        {"header": "subject", "contains": "Tentative:"},
                        {"header": "subject", "contains": "Declined:"},
                    ]
                },
            ]
        }

        # Should NOT match - from doesn't match (even though subject would)
        result = _evaluate_condition_node(header, condition, {}, "")
        assert result is False

    def test_evaluator_rejects_when_subject_no_match(self):
        """Test evaluation fails when none of the OR'd subjects match."""
        header = {
            "from": "steve.gibson@metoffice.gov.uk",
            "subject": "Other Subject",
        }

        condition = {
            "all": [
                {
                    "header": "from",
                    "contains": "steve.gibson@metoffice.gov.uk",
                },
                {
                    "any": [
                        {"header": "subject", "contains": "Accepted:"},
                        {"header": "subject", "contains": "Tentative:"},
                        {"header": "subject", "contains": "Declined:"},
                    ]
                },
            ]
        }

        # Should NOT match - subject doesn't match any in the OR group
        result = _evaluate_condition_node(header, condition, {}, "")
        assert result is False

    def test_evaluator_with_tentative(self):
        """Test evaluation matches Tentative: subject."""
        header = {
            "from": "steve.gibson@metoffice.gov.uk",
            "subject": "Tentative: Board Meeting",
        }

        condition = {
            "all": [
                {
                    "header": "from",
                    "contains": "steve.gibson@metoffice.gov.uk",
                },
                {
                    "any": [
                        {"header": "subject", "contains": "Accepted:"},
                        {"header": "subject", "contains": "Tentative:"},
                        {"header": "subject", "contains": "Declined:"},
                    ]
                },
            ]
        }

        result = _evaluate_condition_node(header, condition, {}, "")
        assert result is True

    def test_evaluator_with_declined(self):
        """Test evaluation matches Declined: subject."""
        header = {
            "from": "steve.gibson@metoffice.gov.uk",
            "subject": "Declined: Team Lunch",
        }

        condition = {
            "all": [
                {
                    "header": "from",
                    "contains": "steve.gibson@metoffice.gov.uk",
                },
                {
                    "any": [
                        {"header": "subject", "contains": "Accepted:"},
                        {"header": "subject", "contains": "Tentative:"},
                        {"header": "subject", "contains": "Declined:"},
                    ]
                },
            ]
        }

        result = _evaluate_condition_node(header, condition, {}, "")
        assert result is True


class TestRuleGenerationAndEvaluation:
    """Test that generated rules work end-to-end with the evaluator."""

    def test_generate_user_requested_rule(self):
        """Test generating the exact rule user requested."""
        builder = RuleBuilder()
        builder.set_name("Cal Responses")
        builder.set_priority(100)

        # Add the exact conditions user wants
        builder.add_condition("from", "contains", "steve.gibson@metoffice.gov.uk")
        builder.add_condition("subject", "contains", "Accepted:")
        builder.add_condition("subject", "contains", "Tentative:")
        builder.add_condition("subject", "contains", "Declined:")
        builder.add_action("move", "Cal Responses")

        # Group: FROM alone (any), SUBJECT patterns (any)
        # Overall: all must match
        grouping = GroupingSpec(
            groups=[
                ConditionGroup(indices=[0], logic="any"),
                ConditionGroup(indices=[1, 2, 3], logic="any"),
            ],
            overall_logic="all",
        )
        builder.finalize_conditions(grouping)

        rule = builder.generate_rule()

        # Verify structure
        assert rule["name"] == "Cal Responses"
        assert rule["priority"] == 100
        assert "conditions" in rule
        assert "all" in rule["conditions"]

        conditions = rule["conditions"]["all"]
        assert len(conditions) == 2

        # First should be FROM condition
        assert conditions[0]["header"] == "from"
        assert "steve.gibson@metoffice.gov.uk" in conditions[0]["contains"]

        # Second should be ANY group of subjects
        assert "any" in conditions[1]
        assert len(conditions[1]["any"]) == 3

        subjects = conditions[1]["any"]
        assert any("Accepted:" in s.get("contains", "") for s in subjects)
        assert any("Tentative:" in s.get("contains", "") for s in subjects)
        assert any("Declined:" in s.get("contains", "") for s in subjects)

    def test_generated_rule_validates_in_evaluator(self):
        """Test that generated nested rule works with evaluator."""
        builder = RuleBuilder()
        builder.set_name("Cal Responses")
        builder.add_condition("from", "contains", "steve.gibson@metoffice.gov.uk")
        builder.add_condition("subject", "contains", "Accepted:")
        builder.add_condition("subject", "contains", "Tentative:")
        builder.add_condition("subject", "contains", "Declined:")
        builder.add_action("move", "Cal Responses")

        grouping = GroupingSpec(
            groups=[
                ConditionGroup(indices=[0], logic="any"),
                ConditionGroup(indices=[1, 2, 3], logic="any"),
            ],
            overall_logic="all",
        )
        builder.finalize_conditions(grouping)
        rule = builder.generate_rule()

        # Test matching case
        header_match = {
            "from": "steve.gibson@metoffice.gov.uk",
            "subject": "Accepted: Meeting",
        }
        result = _evaluate_condition_node(
            header_match, rule["conditions"], {}, ""
        )
        assert result is True

        # Test non-matching FROM
        header_no_from = {
            "from": "other@example.com",
            "subject": "Accepted: Meeting",
        }
        result = _evaluate_condition_node(
            header_no_from, rule["conditions"], {}, ""
        )
        assert result is False

        # Test non-matching SUBJECT
        header_no_subject = {
            "from": "steve.gibson@metoffice.gov.uk",
            "subject": "Other Subject",
        }
        result = _evaluate_condition_node(
            header_no_subject, rule["conditions"], {}, ""
        )
        assert result is False

    def test_simple_flat_rule_still_works(self):
        """Test backward compatibility - simple flat rules still work."""
        builder = RuleBuilder()
        builder.set_name("Simple Newsletter")
        builder.add_condition("from", "contains", "newsletter@example.com")
        builder.add_action("move", "Newsletters")

        rule = builder.generate_rule()

        # Root nodes wrap conditions now (for validation compatibility)
        conditions = rule["conditions"]
        assert "any" in conditions  # Root wraps even single condition
        assert len(conditions["any"]) == 1
        assert conditions["any"][0]["header"] == "from"

        # Should work with evaluator
        header_match = {"from": "newsletter@example.com"}
        result = _evaluate_condition_node(header_match, rule["conditions"], {}, "")
        assert result is True

    def test_multiple_conditions_any_logic(self):
        """Test flat rule with ANY logic still works."""
        builder = RuleBuilder()
        builder.set_name("Newsletter OR Promo")
        builder.add_condition("from", "contains", "newsletter@example.com")
        builder.add_condition("from", "contains", "promo@example.com")
        builder.set_logic("any")
        builder.add_action("move", "Marketing")

        rule = builder.generate_rule()

        conditions = rule["conditions"]
        assert "any" in conditions
        assert len(conditions["any"]) == 2

        # Should match first sender
        header1 = {"from": "newsletter@example.com"}
        result = _evaluate_condition_node(header1, rule["conditions"], {}, "")
        assert result is True

        # Should match second sender
        header2 = {"from": "promo@example.com"}
        result = _evaluate_condition_node(header2, rule["conditions"], {}, "")
        assert result is True

        # Should not match other sender
        header3 = {"from": "other@example.com"}
        result = _evaluate_condition_node(header3, rule["conditions"], {}, "")
        assert result is False

    def test_multiple_conditions_all_logic(self):
        """Test flat rule with ALL logic."""
        builder = RuleBuilder()
        builder.set_name("Important Newsletter")
        builder.add_condition("from", "contains", "newsletter@example.com")
        builder.add_condition("subject", "contains", "important")
        builder.set_logic("all")
        builder.add_action("move", "VIP")

        rule = builder.generate_rule()

        conditions = rule["conditions"]
        assert "all" in conditions
        assert len(conditions["all"]) == 2

        # Should match both conditions
        header_both = {
            "from": "newsletter@example.com",
            "subject": "Important Update",
        }
        result = _evaluate_condition_node(header_both, rule["conditions"], {}, "")
        assert result is True

        # Should not match - missing subject
        header_no_subject = {"from": "newsletter@example.com", "subject": "Regular"}
        result = _evaluate_condition_node(
            header_no_subject, rule["conditions"], {}, ""
        )
        assert result is False

        # Should not match - missing FROM
        header_no_from = {
            "from": "other@example.com",
            "subject": "Important",
        }
        result = _evaluate_condition_node(
            header_no_from, rule["conditions"], {}, ""
        )
        assert result is False


class TestRuleJSONValidation:
    """Test that generated rules produce valid JSON structures."""

    def test_generated_rule_is_valid_json(self):
        """Test generated rules can be serialized/deserialized as JSON."""
        builder = RuleBuilder()
        builder.set_name("Test Rule")
        builder.add_condition("from", "contains", "test@example.com")
        builder.add_condition("subject", "contains", "pattern")
        builder.set_logic("any")
        builder.add_action("move", "Test/Folder")

        rule = builder.generate_rule()

        # Should be JSON-serializable
        json_str = json.dumps(rule)
        parsed = json.loads(json_str)

        # Should have all required fields
        assert parsed["name"] == rule["name"]
        assert parsed["priority"] == rule["priority"]
        assert parsed["conditions"] == rule["conditions"]
        assert parsed["action"] == rule["action"]

    def test_nested_rule_is_valid_json(self):
        """Test nested rules can be serialized/deserialized as JSON."""
        builder = RuleBuilder()
        builder.set_name("Nested Test")
        builder.add_condition("from", "contains", "sender@example.com")
        builder.add_condition("subject", "contains", "urgent")
        builder.add_condition("subject", "contains", "important")
        builder.add_action("move", "Priority")

        grouping = GroupingSpec(
            groups=[
                ConditionGroup(indices=[0], logic="any"),
                ConditionGroup(indices=[1, 2], logic="any"),
            ],
            overall_logic="all",
        )
        builder.finalize_conditions(grouping)
        rule = builder.generate_rule()

        # Should be JSON-serializable
        json_str = json.dumps(rule)
        parsed = json.loads(json_str)

        # Should maintain structure
        assert "all" in parsed["conditions"]
        assert len(parsed["conditions"]["all"]) == 2
        assert "any" in parsed["conditions"]["all"][1]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
